### ISSUE TITLE
Quarto Notebooks

### ISSUE THREAD

**Issue by mavam** [tenzir/public-roadmap#10]
We have a workflow that makes it easy to use VAST from notebooks.

### :100: Definition of Done

- [ ] VAST ships with 3 example Quarto notebooks.
  - [ ] Easy: run a few point queries for IoCs, aggregate and display.
  - [ ] Intermediate: perform a multi-stage hunt with lateral movement.
  - [ ] Advanced: use data-science tooling, e.g., [UMAP](https://umap-learn.readthedocs.io/) for clustering.

**Comment by dominiklohmann** [comment]
Closing as we are not currently pursuing this.
