### ISSUE TITLE
Native Debian Installation

### ISSUE THREAD

**Issue by tobim** [tenzir/public-roadmap#101]
Some users get deterred from websites that ask them to curl a shell script into `/bin/sh`.

The Debian specialized way of `apt-key adv` -> `add-apt-repository` -> `apt update` -> `apt install` has more user trust because it protects their systems from ill-intended or buggy installer code.

We want to support this workflow, with goal that users can install Tenzir as follows:

```bash
apt install tenzir
```

```[tasklist]
### Definition of Done
- [ ] Set up the repository.
- [ ] Integrate with our CI/CD workflow.
- [ ] Update installation instructions.
```

**Comment by mavam** [comment]
Not enough bang for the back for this, closing.
