### ISSUE TITLE
Pipeline Labels

### ISSUE THREAD

**Issue by dominiklohmann** [tenzir/public-roadmap#105]
The overview page can currently be quite overwhelming with many pipelines. We identified two reasons for this:
1. The pipeline definitions are not well readable when horizontal scrolling is required
2. Pipelines that fit together cannot be viewed together

We want to solve both in one go by moving the pipeline definition into the expanded pipeline view, and replacing the now freed up space with user-provided pipeline labels and pipeline uptime.

Here is an early Excalidraw mock from initial discussions about this feature (in particular the area marked in red):

![Image](https://user-images.githubusercontent.com/4488655/268573088-c2048714-ffac-4c63-aba9-aa4fb00b7913.png)

```[tasklist]
### Definition of Done
- [x] Agree on the desired UI and UX
- [x] Implement changes for labels and uptime in the pipeline manager APIs
- [x] Implement changes in the frontend
```

**Comment by dominiklohmann** [comment]
One really small but useful idea that just occurred to me in a call with @mavam: We can let operators provide _auto labels_ that we use by default when creating a pipeline. For example, `load` and `from` can provide their connector as a label, and `from` and `read` their format. It's a simple addition to the operator API that we think can go quite far.

**Comment by annadehtiarova** [comment]
Design for pipeline labels is ready [here](https://www.figma.com/file/aJZUwVbVhRbxPm8zeF5zzO/Product?type=design&node-id=6324-45907&mode=dev)
