### ISSUE TITLE
Deduplication Operator

### ISSUE THREAD

**Issue by mavam** [tenzir/public-roadmap#108]
Deduplication of events according to a given set of keys is a common way to reduce the volume downstream. A `dedupe` operator can achieve this function.

```[tasklist]
### Definition of Done
- [x] Look at the equivalent functionality at [Splunk](https://docs.splunk.com/Documentation/SplunkCloud/latest/SearchReference/dedup), [Cribl](https://docs.cribl.io/search/dedup/) ([blog](https://cribl.io/blog/streaming-data-deduplication-with-cribl/)), and others
- [x] Design the deduplication mechanism (e.g., compound record hash, hash table expiry, etc.)
- [x] Agree on the operator UX
- [x] Implement and test the operator
```

**Comment by mavam** [comment]
A Discord user [asked for this feature](https://discord.com/channels/1072605116978442320/1072605117817290784/1161760323628449975).

**Comment by mavam** [comment]
This came up indirectly again in a strategic partner discussion.

**Comment by dominiklohmann** [comment]
This came up again in a call with a prospect. I've moved this back up to discussion.
