### ISSUE TITLE
Zeek Integration

### ISSUE THREAD

**Issue by mavam** [tenzir/public-roadmap#11]
Zeek provides in-depth network visibility and comes with flexible runtime to control traffic processing. The Zeek App taps into subsets of Zeek's telemetry stream and injects threat intel deep into the runtime.

### :100: Definition of Done

- [ ] The app's attached VAST node ingests Zeek logs
- [ ] The fabric subscribes to notices and publishes them as alerts

**Comment by dominiklohmann** [comment]
Closing as we are not currently pursuing this.
