### ISSUE TITLE
Python Operator

### ISSUE THREAD

**Issue by dominiklohmann** [tenzir/public-roadmap#110]
To make prototyping easier, we want to add a `python` operator that allows for modifying events one at a time. We are aiming at a syntax like this:

```
python '
  foo = x * y
  bar = sqrt(foo)
'
```

Which given the input `{"x": 2, "y": 8}` should result in `{"x": 2, "y": 8, "foo": 16, "bar": 4}`. This is an enabler for the [Dashboard Page](tenzir/private-roadmap#70) for which we are likely to need more flexible data transformations than TQL currently allows.

```[tasklist]
### Definition of Done
- [x] Agree on the desired semantics and syntax
- [x] Implement the operator
- [x] Write documentation
```

**Comment by tobim** [comment]
Blog post idea: Use `pywhois` to retrieve the AS Names of public IP addresses.
