### ISSUE TITLE
Dashboards

### ISSUE THREAD

**Issue by mavam** [tenzir/public-roadmap#139]
In addition to the pipeline overview, we need a high-level dashboard page with management-grade KPIs.

We are looking to build this out as an evolution of the Explorer and Data Visualizer, and want to allow users to pin results to a dashboard. Initially, this will be restricted to historical data sets only, i.e., charts will not update live.

```[tasklist]
### Stories
- [x] https://github.com/tenzir/issues/issues/1105
- [ ] https://github.com/tenzir/issues/issues/1437
- [ ] https://github.com/tenzir/issues/issues/1229
- [ ] https://github.com/tenzir/issues/issues/1253
- [ ] https://github.com/tenzir/issues/issues/1596
- [ ] https://github.com/tenzir/issues/issues/1585
- [ ] https://github.com/tenzir/issues/issues/1653
- [ ] https://github.com/tenzir/issues/issues/1637
- [ ] https://github.com/tenzir/issues/issues/1691
- [ ] https://github.com/tenzir/issues/issues/1256
- [ ] https://github.com/tenzir/issues/issues/1647
- [ ] https://github.com/tenzir/issues/issues/1227
- [ ] https://github.com/tenzir/issues/issues/1839
- [ ] https://github.com/tenzir/issues/issues/1838
- [ ] https://github.com/tenzir/issues/issues/1651
- [ ] https://github.com/tenzir/issues/issues/1789
- [ ] https://github.com/tenzir/issues/issues/1863
```

**Comment by mavam** [comment]
Should we add the story on grouped & stacked bar charts to this epic? ARo also said it's important to him.

**Comment by dit7ya** [comment]
Here they are.

https://github.com/tenzir/issues/issues/1838

https://github.com/tenzir/issues/issues/1839

**Comment by mavam** [comment]
Can you update the story list in the OP with that? Otherwise the current state is difficult to capture.
