### ISSUE TITLE
First-class Scheduler

### ISSUE THREAD

**Issue by mavam** [tenzir/public-roadmap#14]
After splitting out partition and store building from the catalog, we can rename the index to scheduler and make sure it is (1) downstream of the catalog and (2) solely responsible for scheduling.

Note that this is a technically motivated roadmap item that exists to remove technical debt.

```[tasklist]
### Definition of Done
- [ ] The `import` operator talks to the catalog directly
- [ ] The `export` operator talks to the catalog directly
- [ ] The scheduler has the sole responsibility of query & partition management
- [ ] The index is removed
```

**Comment by dominiklohmann** [comment]
This is superseded by https://github.com/tenzir/public-roadmap/issues/104
