### ISSUE TITLE
UDP Connector

### ISSUE THREAD

**Issue by mavam** [tenzir/public-roadmap#143]
Similar to our TCP connector, we need a UDP connector.

```[tasklist]
### Tasks
- [x] `udp` loader
- [x] `udp` saver
```

**Comment by mavam** [comment]
We heard a request for this because many devices (e.g., Firewalls) only support UDP-based export of logs, often via syslog.

**Comment by dominiklohmann** [comment]
We do not currently have a demand for this. Closing for now.
