### ISSUE TITLE
YAML Modules

### ISSUE THREAD

**Issue by mavam** [tenzir/public-roadmap#15]
Except for schemas, all of VAST's configuration is in YAML. We want to replace VAST's custom schema DSL with a YAML equivalent, and introduce namespaces ("modules") while we're at it.

```[tasklist]
### Definition of Done
- [x] There exists a YAML type definition convention.
- [x] VAST can generate its known type definitions via `vast show`.
- [ ] There exists a namespacing/grouping mechanism for types (aka. *modules*).
- [ ] The old schema language is deprecated.
```

**Comment by dominiklohmann** [comment]
We are not pursuing this right now. To be reconsidered as part of TQL.
