### ISSUE TITLE
Query Pagination

### ISSUE THREAD

**Issue by mavam** [tenzir/public-roadmap#16]
In order to make the REST API (tenzir/public-roadmap#29) usable for queries, we need to provide a paginated query interface.

### Definition of Done

- [ ] A new `vast query` command allows for interaction with a remote query.
   - [ ] Spawn a query.
   - [ ] Extract data in a paginated fashion (with input iterator semantics)
- [ ] The new command is suitable for controlling via the REST API

**Comment by dominiklohmann** [comment]
We merged this into the larger scope of tenzir/private-roadmap#9.
