### ISSUE TITLE
Pipeline Design

### ISSUE THREAD

**Issue by mavam** [tenzir/public-roadmap#17]
A common database feature is being able to work with the data rather than just extracting this. We already have pipeline operators that were built for the compaction use case, and we want to expand on this design by (1) exposing them to the user on the CLI and (2) coming up with a medium-term goal for where we want to end up with pipelines.

### Definition of Done

- [x] For (1), we have a design for how users can run pipelines directly from the command-line:
  - [x] We agreed on how we want to configure all the individual operators.
  - [x] We agreed on the design for the pipeline executor: tenzir/vast#2600
- [x] For (2), we want to create an RFC for public discussion with our vision:
  - [x] There exist an RFC: https://github.com/tenzir/vast/pull/2511
  - [x] The RFC has been accepted

**Comment by dominiklohmann** [comment]
I am closing this out as we're done with the design phase. We've arrived at an implementation plan laid out in tenzir/vast#2600 which we plan to implement as part of #18 in Q4 2022.
