### ISSUE TITLE
OCSF Normalization

### ISSUE THREAD

**Issue by mavam** [tenzir/public-roadmap#2]
OCSF is becoming the de-facto event taxonomy. We would like to supports it first-class so that users have the choice to transform their data into OCSF. 

```[tasklist]
### Definition of Done
- [ ] Define the right pipeline operators to reshape the data.
- [ ] Programatically derive the needed pipeline configuration/setup from the OCSF data.
- [ ] Normalize Suricata data.
- [ ] Normalize Zeek data.
```

**Comment by dominiklohmann** [comment]
We heard a related request for CIM normalization from a prospect today. @mavam and I previously discussed wanting to normalize to OCSF first and then going to other taxonomies from there to only have $`n+m`$ rather than $`n*m`$ mappings.

**Comment by zschmerber** [comment]
@dominiklohmann Splunk is working on an OCSF to CIM app that you could use the logic from, I think raw->OCSF->CIM is not ideal but the logic would be maintained with out much support needed. https://apps.splunk.com/app/6841/

**Comment by mavam** [comment]
@zschmerber yeah, our current thinking is to carry the original data along the way and drop it consciously at a later point in time. But to turn the multiplicative into an additive problem, we'd argue OCSF first, and then we can still later engage the community to do the OCSF → X mappings, where X might be ECS, CIM, LEEF, UDM, etc.

**Comment by mavam** [comment]
This roadmap item is now covered by various other ones. With the advent of the library, packages will provide pipelines that map to OCSF.
