### ISSUE TITLE
Parquet & Feather Stores

### ISSUE THREAD

**Issue by mavam** [tenzir/public-roadmap#24]
VAST's data model is based on Apache Arrow. We want to re-use industry standard tooling for persisting Arrow tables, which are Apache Feather V2 and Apache Parquet. We aim to make Apache Feather V2 the replacement of the current hand-rolled Segment Store.

### :100: Definition of Done

- [x] We implemented an Apache Feather V2 store backend.
- [x] We implemented an Apache Parquet store backend.
- [x] We tested the performance and correctness of the new store backends.
- [x] Apache Feather V2 is the default store backend.
- [x] The Segment Store is deprecated and read-only.

**Comment by dominiklohmann** [comment]
This has been merged to master in VAST, and will be in the upcoming VAST v2.4 release.
