### ISSUE TITLE
Time-dependent Passive DNS

### ISSUE THREAD

**Issue by mavam** [tenzir/public-roadmap#28]
Build a passive DNS database from entity events.

### :100: Definition of Done

- [ ] Scope: IP ⇄ Hostname mappings are linked from entity events
- [ ] State is bucketed by time
- [ ] Buckets can be merged to provide different views, e.g., hour/day/week
- [ ] Users can fuse this data into a pipeline

**Comment by dominiklohmann** [comment]
Closing as we are not currently pursuing this.
