### ISSUE TITLE
OpenSSF Silver Badge

### ISSUE THREAD

**Issue by mavam** [tenzir/public-roadmap#32]
We wan to pass the OpenSSF [Silver Badge criteria](https://bestpractices.coreinfrastructure.org/en/criteria/1)—it's excellent marketing material, and a good check on us being a good open-source citizen.

### :100: Definition of Done

We pass the [requirements](https://bestpractices.coreinfrastructure.org/en/projects/6366?criteria_level=1) list for the Silver Badge

- [ ] Basics
- [x] Change Control
- [x] Reporting
- [ ] Quality
- [ ] Security
- [x] Analysis

**Comment by dominiklohmann** [comment]
Closing as we are not currently pursuing this.
