### ISSUE TITLE
Catalog Partition Ownership

### ISSUE THREAD

**Issue by mavam** [tenzir/public-roadmap#34]
VAST's partitions are currently owned by the index, which is responsible for both handling queries, partition ownership, and dispatching and synchronizing partition metadata updates to and with the catalog.

We want to simply this approach by making the catalog own the partitions, and further simplify by integrating the type-registry functionality into the catalog.

### :100: Definition of Done

- [x] Merge type registry into catalog.
- [ ] Unify extractor semantics and bind expressions once per unique schema.
- [ ] Separate partition ownership from actor logic.
- [ ] Move store ownership into partitions.
- [ ] Migrate partition ownership from index to catalog.
- [ ] Remove support for querying active partitions.
- [ ] Make catalog the first point of query.

**Comment by dominiklohmann** [comment]
We have split this out into a draft item for Fault Tolerance and moved the extractor semantics changes into #18.
