### ISSUE TITLE
Query Variable Templates

### ISSUE THREAD

**Issue by mavam** [tenzir/public-roadmap#42]
As a power user, a frequent use case involves repeating a query where only a small part changes. While it is always possible to generate templated queries out of VAST, it would nice if there is first-class support built-in. This would allow for more powerful template variable interpolation with context that is only known to VAST.

### :100: Definition of Done

- [ ] We have an accepted RFC describing the mechanism
- [ ] We have implemented the agreed upon solution

**Comment by dominiklohmann** [comment]
Closing as we are considering other options for this as part of the Expressions and User-defined Operator roadmap items.
