### ISSUE TITLE
STIX Patterns Operator

### ISSUE THREAD

**Issue by mavam** [tenzir/public-roadmap#46]
[STIX Patterns](https://docs.oasis-open.org/cti/stix/v2.1/os/stix-v2.1-os.html#_e8slinrhxcc9) are an established way to express queries about entities. For example, this is an Observation Expression:

```
[ipv4-addr:value = '198.51.100.1/32' OR ipv4-addr:value = '203.0.113.33/32' OR ipv6-addr:value = '2001:0db8:dead:beef:dead:beef:dead:0001/128']
```

We want to have a language frontend that supports translation of such a pattern into a [TQL expression](https://vast.io/docs/understand/language/expressions):

```
198.51.100.1 || 203.0.113.33 || 2001:0db8:dead:beef:dead:beef:dead:0001
```

Out of scope are initially more advanced qualifiers, like `REPEATS` and `WITHIN`, as well as the Observation Expression operator `FOLLOWEDBY`. However, devising a plan on how to treat them could be a stretch goal.

A final topic concerns STIX Bundles. Tenzir should accept them and treat them as large disjunction, to simplify the use case of checking a set of observables in bulk.

```[tasklist]
### Definition of Done
- [ ] Design STIX Patterns operator UX
- [ ] Implement STIX Patterns operator
```

**Comment by dominiklohmann** [comment]
As part of this, we should look at the following parts of the specification:

- Comparison Expressions: ipv4-addr:value = '198.51.100.1/32'
  - Object Path
  - Comparison Operators
    - <, <=, >=, >
    - ==, !=
    - EXISTS maps to a field extractor predicate or field != nil
    - ISSUBSET maps to in
    - ISSUPERSET(x,y) maps to y in x for subnet types
    - MATCHES(x, y) maps to x == /y/
  - Constant translation
- Observation Expression: [A OR B AND C AND NOT D]
  - START and STOP qualifiers
  - STIX Bundles as VAST expressions: disjunction
-  Devise plan for REPEATS and WITHIN qualifiers
-  Devise plan for FOLLOWEDBY Observation Operators

**Comment by dominiklohmann** [comment]
We have no demand for this currently. Closing for now.
