### ISSUE TITLE
Group Operator

### ISSUE THREAD

**Issue by dominiklohmann** [tenzir/public-roadmap#62]
We want a standalone group operator that splits input into multiple instances of a nested pipeline.

### 💯 Definition of Done

```[tasklist]
- [ ] Design a mechanism for nested pipeline execution
- [ ] Design syntax for nested pipelines
- [ ] Implement a standalone `group` operator
```

**Comment by mavam** [comment]
Since this issue mentions "nested pipelines", I want to point out https://github.com/orgs/tenzir/discussions/3413.

**Comment by dominiklohmann** [comment]
This and the `window` operator for windowing came up again in a call with a prospect. It's clear that they're the top priorities after TQL2 is ready.

**Comment by dominiklohmann** [comment]
Closing in favor of https://github.com/tenzir/private-roadmap/issues/68
