### ISSUE TITLE
Pipeline Warnings

### ISSUE THREAD

**Issue by dominiklohmann** [tenzir/public-roadmap#71]
This is a follow-up to https://github.com/tenzir/public-roadmap/issues/61

We want to make it possible for users to see warnings from pipelines in the explorer and the overview. For this, we want to take a look at the following:

- Display warnings: Either in the context pane, or where we currently show the data table, with a toggle to switch between warnings and errors.
- Add rich display for hints and docs.
- Visually link between warnings and the editor for annotated diagnostics.
- Render warnings and errors for the overview page.
- Implement a mechanism to mark warnings as read.

```[tasklist]
### Stories
- [ ] https://github.com/tenzir/issues/issues/1517
- [ ] https://github.com/tenzir/issues/issues/1516
- [ ] https://github.com/tenzir/issues/issues/944
- [ ] https://github.com/tenzir/issues/issues/1708
- [ ] https://github.com/tenzir/issues/issues/1840
- [ ] https://github.com/tenzir/issues/issues/1841
- [ ] https://github.com/tenzir/issues/issues/1842
- [ ] https://github.com/tenzir/issues/issues/2051
- [ ] https://github.com/tenzir/issues/issues/2052
- [ ] https://github.com/tenzir/issues/issues/1843
- [ ] https://github.com/tenzir/issues/issues/1844
- [ ] https://github.com/tenzir/issues/issues/1845
- [ ] https://github.com/tenzir/issues/issues/1846
- [ ] https://github.com/tenzir/issues/issues/1847
- [ ] https://github.com/tenzir/issues/issues/1848
- [ ] https://github.com/tenzir/issues/issues/1927
- [ ] https://github.com/tenzir/issues/issues/1928
- [ ] https://github.com/tenzir/issues/issues/1930
```

**Comment by Avaq** [comment]
Referencing this related comment on a PR review, so we don't lose track of it: https://github.com/tenzir/app/pull/601#discussion_r1594071654
