### ISSUE TITLE
PCAPng Format

### ISSUE THREAD

**Issue by mavam** [tenzir/public-roadmap#75]
When we switched from parsing packets with libpcap to our custom PCAP parser, we lost the ability to process PCAPng files that we inherited via libpcap. We should bring this capability back.

**Comment by mavam** [comment]
Jasper and Anthony requested this feature in our community Discord.

**Comment by dominiklohmann** [comment]
There is no acute need for this right now. There's a conversion workaround available. Closing until a customer need for this appears.
