### ISSUE TITLE
Email Saver

### ISSUE THREAD

**Issue by mavam** [tenzir/public-roadmap#77]
Sending pipeline results via email is a useful capability to deliver important events to the inbox of an operator. To this end, we would like to implement the `email` saver.

```[tasklist]
### Definition of Done
- [x] Define the CLI UX
- [x] Implement the email sending logic using [libcurl](https://curl.se/libcurl/c/smtp-mail.html)
```

**Comment by mavam** [comment]
A Discord user mentioned that it would be useful to have this capability in the future.

**Comment by dominiklohmann** [comment]
We have no need for this currently.

**Comment by mavam** [comment]
Reopening because the need came back up again.
